site_name: wallp

dev_addr: 0.0.0.0:8090

pages:
- 'index.md'
- Installation: 'install.md'
- Basic Usage: 'usage.md'
- Commands:
        - change: 'change.md'
        - schedule: 'schedule.md'
        - info: 'info.md'
        - like / dislike: 'like_dislike.md'
        - keep: 'keep.md'
        - list: 'list2.md'
        - add / enable / disable: 'list.md'
        - log: 'log.md'
        - get: 'get.md'
        - set: 'set.md'
        - db: 'db.md'
- Change Log: 'changelog.md'

